version = 5.0.0
archive_dir = /Users/davidhall/Desktop/Tennis Club Map/.letsencrypt/config/archive/tennisclubconnect.com
cert = /Users/davidhall/Desktop/Tennis Club Map/.letsencrypt/config/live/tennisclubconnect.com/cert.pem
privkey = /Users/davidhall/Desktop/Tennis Club Map/.letsencrypt/config/live/tennisclubconnect.com/privkey.pem
chain = /Users/davidhall/Desktop/Tennis Club Map/.letsencrypt/config/live/tennisclubconnect.com/chain.pem
fullchain = /Users/davidhall/Desktop/Tennis Club Map/.letsencrypt/config/live/tennisclubconnect.com/fullchain.pem
[renewalparams]
account = eec344d1c72c66d8e206296eef692324
pref_challs = dns-01,
config_dir = /Users/davidhall/Desktop/Tennis Club Map/.letsencrypt/config
work_dir = /Users/davidhall/Desktop/Tennis Club Map/.letsencrypt/work
logs_dir = /Users/davidhall/Desktop/Tennis Club Map/.letsencrypt/logs
authenticator = manual
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[acme_renewal_info]
ari_retry_after = 2025-09-18T05:12:12
